<<<<<<< HEAD
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
sphinx:
  configuration: source/conf.py
python:
  install:
    - requirements: source/requirements.txt

=======
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
sphinx:
  configuration: source/conf.py
python:
  install:
    - requirements: source/requirements.txt

>>>>>>> 609ef723c6857495dd240d32ea496d6eba393a4d
        